# Generated by Django 2.0.3 on 2018-03-12 15:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloklapangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop_field', models.CharField(max_length=50)),
                ('d_nop', models.CharField(max_length=50)),
                ('blok', models.CharField(max_length=50)),
                ('num', models.FloatField()),
                ('nop', models.CharField(max_length=254)),
                ('wajibpajak', models.CharField(max_length=254, verbose_name='Wajib Pajak ')),
                ('nik', models.CharField(max_length=254, verbose_name='NIK ')),
                ('alamat', models.CharField(max_length=254)),
                ('luasbumi', models.CharField(max_length=254)),
                ('luasbangun', models.CharField(max_length=254)),
                ('jumlahlant', models.CharField(max_length=254)),
                ('kondisiata', models.CharField(max_length=254)),
                ('kondisidin', models.CharField(max_length=254)),
                ('jenislanta', models.CharField(max_length=254)),
                ('keterangan', models.CharField(max_length=254)),
                ('penghuni', models.CharField(max_length=254)),
                ('pria', models.CharField(max_length=254)),
                ('wanita', models.CharField(max_length=254)),
                ('difabel', models.CharField(max_length=254)),
                ('sumberair', models.CharField(max_length=254)),
                ('jamban', models.CharField(max_length=254)),
                ('sampah', models.CharField(max_length=254)),
                ('pekerjaan', models.CharField(max_length=254)),
                ('kesehatan', models.CharField(max_length=254)),
                ('pendidikan', models.CharField(max_length=254)),
                ('penguasaan', models.CharField(max_length=254)),
                ('legalitasb', models.CharField(max_length=254)),
                ('lahanbng', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Baseline',
            },
        ),
        migrations.CreateModel(
            name='Incindences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Incidences',
            },
        ),
        migrations.CreateModel(
            name='Umum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=254)),
                ('kelurahan', models.CharField(max_length=254)),
                ('lingkungan', models.CharField(max_length=254)),
                ('jumlah', models.FloatField()),
                ('penduduk_laki_laki', models.FloatField()),
                ('penduduk_perempuan', models.FloatField()),
                ('disabilitas', models.FloatField()),
                ('satuan1', models.CharField(max_length=254)),
                ('pertanian', models.FloatField()),
                ('perikanan', models.FloatField()),
                ('tambang', models.FloatField()),
                ('industri', models.FloatField()),
                ('konstruksi', models.FloatField()),
                ('perdagangan', models.FloatField()),
                ('pemerintah', models.FloatField()),
                ('dalam_kel', models.FloatField()),
                ('luar_kel', models.FloatField()),
                ('kota_luar', models.FloatField()),
                ('tidak_sekolah', models.FloatField()),
                ('tidak_ada_angg', models.FloatField()),
                ('satuan2', models.CharField(max_length=254)),
                ('luas', models.IntegerField()),
                ('kepadatan_penduduk', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name_plural': 'Umum',
            },
        ),
    ]
