# Generated by Django 2.0.3 on 2018-03-13 10:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_x', models.FloatField()),
                ('point_y', models.FloatField()),
                ('nama_obyek', models.CharField(max_length=254)),
                ('kls_obyek', models.CharField(max_length=254)),
                ('kode', models.CharField(max_length=254)),
                ('no_foto', models.CharField(max_length=254)),
                ('tgl_survey', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=32651)),
            ],
            options={
                'verbose_name': 'Terminal',
            },
        ),
    ]
