# Generated by Django 2.0.3 on 2018-03-13 12:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0002_trterminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchSulut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('area', models.IntegerField()),
                ('toponym', models.CharField(max_length=25)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Patch Sulut',
            },
        ),
    ]
