# Generated by Django 2.0.3 on 2018-03-13 13:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0004_trlampu'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrJembatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_field', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('base', models.FloatField()),
                ('snippet', models.CharField(max_length=254)),
                ('labelid', models.IntegerField()),
                ('folder_pat', models.CharField(max_length=50)),
                ('symbol_id', models.CharField(max_length=50)),
                ('alt_mode', models.CharField(max_length=50)),
                ('pop_up_inf', models.CharField(max_length=50)),
                ('hsl_tabel', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=32651)),
            ],
            options={
                'verbose_name': 'Jembatan',
            },
        ),
    ]
