# Generated by Django 2.0.3 on 2018-03-13 19:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0009_smpsungai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanitasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid_field', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('descript', models.CharField(max_length=254)),
                ('type', models.CharField(max_length=254)),
                ('comment', models.CharField(max_length=254)),
                ('symbol', models.CharField(max_length=254)),
                ('datetimes', models.CharField(max_length=24)),
                ('elevation', models.FloatField()),
                ('keterangan', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=32651)),
            ],
            options={
                'verbose_name': 'Sanitasi',
            },
        ),
    ]
