# Generated by Django 2.0.3 on 2018-04-13 07:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0011_bnbakl'),
    ]

    operations = [
        migrations.CreateModel(
            name='BnbaIstq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50)),
                ('no_rumah', models.CharField(max_length=50)),
                ('lingkungan', models.CharField(max_length=50)),
                ('kode_foto', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
                ('path_foto', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Istiqlal',
            },
        ),
        migrations.CreateModel(
            name='BnbaMhkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50)),
                ('no_rumah', models.CharField(max_length=50)),
                ('lingkungan', models.CharField(max_length=50)),
                ('kode_foto', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
                ('path_foto', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Mahakeret Timur',
            },
        ),
        migrations.CreateModel(
            name='BnbaTelb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50)),
                ('no_rumah', models.CharField(max_length=50)),
                ('lingkungan', models.CharField(max_length=50)),
                ('kode_foto', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
                ('path_foto', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Teling Bawah',
            },
        ),
        migrations.CreateModel(
            name='BnbaTklak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50)),
                ('no_rumah', models.CharField(max_length=50)),
                ('lingkungan', models.CharField(max_length=50)),
                ('kode_foto', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
                ('path_foto', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Tikala Kumaraka',
            },
        ),
        migrations.CreateModel(
            name='BnbaWngsel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50)),
                ('no_rumah', models.CharField(max_length=50)),
                ('lingkungan', models.CharField(max_length=50)),
                ('kode_foto', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
                ('path_foto', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Wenang Selatan',
            },
        ),
        migrations.AlterModelOptions(
            name='bnbakl',
            options={'verbose_name': 'Komo Luar'},
        ),
    ]
