# Generated by Django 2.0.3 on 2018-04-24 08:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0013_auto_20180415_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='BnbaLwng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50)),
                ('no_rumah', models.CharField(max_length=50)),
                ('lingkungan', models.CharField(max_length=50)),
                ('kode_foto', models.CharField(max_length=50)),
                ('stat', models.CharField(max_length=50)),
                ('path_foto', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Lawangirung',
            },
        ),
        migrations.CreateModel(
            name='BnbaWngut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50)),
                ('no_rumah', models.CharField(max_length=50)),
                ('lingkungan', models.CharField(max_length=50)),
                ('kode_foto', models.CharField(max_length=50, null=True)),
                ('stat', models.CharField(max_length=50)),
                ('path_foto', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Wenang Utara',
            },
        ),
    ]
