# Generated by Django 2.0.3 on 2018-05-07 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0017_auto_20180430_0621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bnbatwut',
            options={'verbose_name': 'Titiwungen Utara'},
        ),
        migrations.RenameField(
            model_name='bnbaistq',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='bnbamhkt',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='bnbatelb',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='bnbatklak',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='bnbawngsel',
            old_name='status',
            new_name='Status',
        ),
        migrations.AddField(
            model_name='bnbakl',
            name='Status',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bnbalwng',
            name='kode_foto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbalwng',
            name='path_foto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
