# Generated by Django 2.0.3 on 2018-05-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0019_auto_20180507_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnbacal',
            name='kode_kec',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbacal',
            name='kode_kel',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbacal',
            name='trans_id',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbacal',
            name='upk',
            field=models.BigIntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbaistq',
            name='kode_kec',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbaistq',
            name='kode_kel',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbaistq',
            name='trans_id',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbaistq',
            name='upk',
            field=models.BigIntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbakl',
            name='kode_kec',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbakl',
            name='kode_kel',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbakl',
            name='trans_id',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbakl',
            name='upk',
            field=models.BigIntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbalwng',
            name='kode_kec',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbalwng',
            name='kode_kel',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbalwng',
            name='trans_id',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbalwng',
            name='upk',
            field=models.BigIntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbamhkt',
            name='kode_kec',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbamhkt',
            name='kode_kel',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbamhkt',
            name='trans_id',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbamhkt',
            name='upk',
            field=models.BigIntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbapin',
            name='kode_kec',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbapin',
            name='kode_kel',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbapin',
            name='trans_id',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbapin',
            name='upk',
            field=models.BigIntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatelb',
            name='kode_kec',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatelb',
            name='kode_kel',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatelb',
            name='trans_id',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatelb',
            name='upk',
            field=models.BigIntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatklak',
            name='kode_kec',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatklak',
            name='kode_kel',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatklak',
            name='trans_id',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatklak',
            name='upk',
            field=models.BigIntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatwsel',
            name='kode_kec',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatwsel',
            name='kode_kel',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatwsel',
            name='trans_id',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatwsel',
            name='upk',
            field=models.BigIntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatwut',
            name='kode_kec',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatwut',
            name='kode_kel',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatwut',
            name='trans_id',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbatwut',
            name='upk',
            field=models.BigIntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbawngsel',
            name='kode_kec',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbawngsel',
            name='kode_kel',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbawngsel',
            name='trans_id',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbawngsel',
            name='upk',
            field=models.BigIntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbawngut',
            name='kode_kec',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbawngut',
            name='kode_kel',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbawngut',
            name='trans_id',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bnbawngut',
            name='upk',
            field=models.BigIntegerField(max_length=12, null=True),
        ),
    ]
