# Generated by Django 2.0.3 on 2018-05-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0020_auto_20180507_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnbacal',
            name='kode_kec',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbacal',
            name='kode_kel',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbacal',
            name='trans_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbacal',
            name='upk',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbaistq',
            name='kode_kec',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbaistq',
            name='kode_kel',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbaistq',
            name='trans_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbaistq',
            name='upk',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbakl',
            name='kode_kec',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbakl',
            name='kode_kel',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbakl',
            name='trans_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbakl',
            name='upk',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbalwng',
            name='kode_kec',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbalwng',
            name='kode_kel',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbalwng',
            name='trans_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbalwng',
            name='upk',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkt',
            name='kode_kec',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkt',
            name='kode_kel',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkt',
            name='trans_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkt',
            name='upk',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatelb',
            name='kode_kec',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatelb',
            name='kode_kel',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatelb',
            name='trans_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatelb',
            name='upk',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatklak',
            name='kode_kec',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatklak',
            name='kode_kel',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatklak',
            name='trans_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatklak',
            name='upk',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwsel',
            name='kode_kec',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwsel',
            name='kode_kel',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwsel',
            name='trans_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwsel',
            name='upk',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwut',
            name='kode_kec',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwut',
            name='kode_kel',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwut',
            name='trans_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwut',
            name='upk',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngsel',
            name='kode_kec',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngsel',
            name='kode_kel',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngsel',
            name='trans_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngsel',
            name='upk',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngut',
            name='kode_kec',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngut',
            name='kode_kel',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngut',
            name='trans_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngut',
            name='upk',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
