# Generated by Django 2.0.3 on 2018-05-08 06:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0022_auto_20180508_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cctv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=32651)),
            ],
        ),
        migrations.AlterField(
            model_name='bnbacal',
            name='kode_kec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbacal',
            name='kode_kel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbacal',
            name='trans_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbacal',
            name='upk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbaistq',
            name='kode_kec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbaistq',
            name='kode_kel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbaistq',
            name='trans_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbaistq',
            name='upk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbakl',
            name='kode_kec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbakl',
            name='kode_kel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbakl',
            name='trans_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbakl',
            name='upk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbalwng',
            name='kode_kec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbalwng',
            name='kode_kel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbalwng',
            name='trans_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbalwng',
            name='upk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkt',
            name='kode_kec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkt',
            name='kode_kel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkt',
            name='trans_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkt',
            name='upk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbapin',
            name='kode_kec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbapin',
            name='kode_kel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbapin',
            name='trans_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbapin',
            name='upk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatelb',
            name='kode_kec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatelb',
            name='kode_kel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatelb',
            name='trans_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatelb',
            name='upk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatklak',
            name='kode_kec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatklak',
            name='kode_kel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatklak',
            name='trans_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatklak',
            name='upk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwsel',
            name='kode_kec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwsel',
            name='kode_kel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwsel',
            name='trans_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwsel',
            name='upk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwut',
            name='kode_kec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwut',
            name='kode_kel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwut',
            name='trans_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwut',
            name='upk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngsel',
            name='kode_kec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngsel',
            name='kode_kel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngsel',
            name='trans_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngsel',
            name='upk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngut',
            name='kode_kec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngut',
            name='kode_kel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngut',
            name='trans_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngut',
            name='upk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
