# Generated by Django 2.0.3 on 2018-05-08 09:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0023_auto_20180508_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='BnbaBmib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50)),
                ('no_rumah', models.CharField(max_length=50)),
                ('lingkungan', models.CharField(max_length=50)),
                ('kode_foto', models.CharField(max_length=50, null=True)),
                ('stat', models.CharField(max_length=50)),
                ('path_foto', models.CharField(max_length=50, null=True)),
                ('trans_id', models.CharField(max_length=50, null=True)),
                ('kode_kec', models.CharField(max_length=50, null=True)),
                ('kode_kel', models.CharField(max_length=50, null=True)),
                ('upk', models.CharField(max_length=12, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Bumi Beringin',
            },
        ),
        migrations.CreateModel(
            name='BnbaMhkb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50)),
                ('no_rumah', models.CharField(max_length=50)),
                ('lingkungan', models.CharField(max_length=50)),
                ('kode_foto', models.CharField(max_length=50, null=True)),
                ('stat', models.CharField(max_length=50)),
                ('path_foto', models.CharField(max_length=50, null=True)),
                ('trans_id', models.CharField(max_length=50, null=True)),
                ('kode_kec', models.CharField(max_length=50, null=True)),
                ('kode_kel', models.CharField(max_length=50, null=True)),
                ('upk', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Mahakeret Barat',
            },
        ),
    ]
