# Generated by Django 2.0.3 on 2018-05-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0024_bnbabmib_bnbamhkb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnbabmib',
            name='lingkungan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbabmib',
            name='no_rumah',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbabmib',
            name='nop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbabmib',
            name='stat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbacal',
            name='lingkungan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbacal',
            name='no_rumah',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbacal',
            name='nop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbacal',
            name='stat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbaistq',
            name='lingkungan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbaistq',
            name='no_rumah',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbaistq',
            name='nop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbaistq',
            name='stat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbakl',
            name='lingkungan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbakl',
            name='no_rumah',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbakl',
            name='nop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbakl',
            name='stat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbalwng',
            name='lingkungan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbalwng',
            name='no_rumah',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbalwng',
            name='nop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbalwng',
            name='stat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkb',
            name='lingkungan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkb',
            name='no_rumah',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkb',
            name='nop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkb',
            name='stat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkt',
            name='lingkungan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkt',
            name='no_rumah',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkt',
            name='nop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkt',
            name='stat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbapin',
            name='lingkungan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbapin',
            name='no_rumah',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbapin',
            name='nop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbapin',
            name='stat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatelb',
            name='lingkungan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatelb',
            name='no_rumah',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatelb',
            name='nop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatelb',
            name='stat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatklak',
            name='lingkungan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatklak',
            name='no_rumah',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatklak',
            name='nop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatklak',
            name='stat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwsel',
            name='lingkungan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwsel',
            name='no_rumah',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwsel',
            name='nop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwsel',
            name='stat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwut',
            name='lingkungan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwut',
            name='no_rumah',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwut',
            name='nop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwut',
            name='stat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngsel',
            name='lingkungan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngsel',
            name='no_rumah',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngsel',
            name='nop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngsel',
            name='stat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngut',
            name='lingkungan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngut',
            name='no_rumah',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngut',
            name='nop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngut',
            name='stat',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
