# Generated by Django 2.0.3 on 2018-05-17 03:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0025_auto_20180509_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swalayan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, null=True)),
                ('keterangan', models.CharField(max_length=50, null=True)),
                ('minimarket', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=32651)),
            ],
            options={
                'verbose_name': 'Swalayan',
            },
        ),
    ]
