# Generated by Django 2.0.3 on 2018-05-21 04:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0028_auto_20180521_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='BnbaRanotana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50, null=True)),
                ('no_rumah', models.CharField(max_length=50, null=True)),
                ('lingkungan', models.CharField(max_length=50, null=True)),
                ('kode_foto', models.CharField(max_length=50, null=True)),
                ('stat', models.CharField(max_length=50, null=True)),
                ('path_foto', models.CharField(max_length=50, null=True)),
                ('trans_id', models.CharField(max_length=50, null=True)),
                ('kode_kec', models.CharField(max_length=50, null=True)),
                ('kode_kel', models.CharField(max_length=50, null=True)),
                ('upk', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Ranotana',
            },
        ),
        migrations.CreateModel(
            name='BnbaSaKobar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50, null=True)),
                ('no_rumah', models.CharField(max_length=50, null=True)),
                ('lingkungan', models.CharField(max_length=50, null=True)),
                ('kode_foto', models.CharField(max_length=50, null=True)),
                ('stat', models.CharField(max_length=50, null=True)),
                ('path_foto', models.CharField(max_length=50, null=True)),
                ('trans_id', models.CharField(max_length=50, null=True)),
                ('kode_kec', models.CharField(max_length=50, null=True)),
                ('kode_kel', models.CharField(max_length=50, null=True)),
                ('upk', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Sario Kotabaru',
            },
        ),
        migrations.CreateModel(
            name='BnbaSario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50, null=True)),
                ('no_rumah', models.CharField(max_length=50, null=True)),
                ('lingkungan', models.CharField(max_length=50, null=True)),
                ('kode_foto', models.CharField(max_length=50, null=True)),
                ('stat', models.CharField(max_length=50, null=True)),
                ('path_foto', models.CharField(max_length=50, null=True)),
                ('trans_id', models.CharField(max_length=50, null=True)),
                ('kode_kec', models.CharField(max_length=50, null=True)),
                ('kode_kel', models.CharField(max_length=50, null=True)),
                ('upk', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Sario',
            },
        ),
        migrations.CreateModel(
            name='BnbaSarTum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50, null=True)),
                ('no_rumah', models.CharField(max_length=50, null=True)),
                ('lingkungan', models.CharField(max_length=50, null=True)),
                ('kode_foto', models.CharField(max_length=50, null=True)),
                ('stat', models.CharField(max_length=50, null=True)),
                ('path_foto', models.CharField(max_length=50, null=True)),
                ('trans_id', models.CharField(max_length=50, null=True)),
                ('kode_kec', models.CharField(max_length=50, null=True)),
                ('kode_kel', models.CharField(max_length=50, null=True)),
                ('upk', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Sario Tumpaan',
            },
        ),
    ]
