# Generated by Django 2.0.3 on 2018-05-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0029_bnbaranotana_bnbasakobar_bnbasario_bnbasartum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnbabmib',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbacal',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbaistq',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbakl',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbalwng',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkb',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbamhkt',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbapin',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbaranotana',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbasakobar',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbasario',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbasartum',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbasarut',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatelb',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatklak',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwsel',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbatwut',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngsel',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbawngut',
            name='path_foto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
