# Generated by Django 2.0.3 on 2018-05-21 06:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0030_auto_20180521_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnbasarut',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=32651),
        ),
    ]
