# Generated by Django 2.0.3 on 2018-05-22 06:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpuljaringan', '0031_auto_20180521_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='BnbaKrgwr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50, null=True)),
                ('no_rumah', models.CharField(max_length=50, null=True)),
                ('lingkungan', models.CharField(max_length=50, null=True)),
                ('kode_foto', models.CharField(max_length=50, null=True)),
                ('stat', models.CharField(max_length=50, null=True)),
                ('path_foto', models.CharField(max_length=100, null=True)),
                ('trans_id', models.CharField(max_length=50, null=True)),
                ('kode_kec', models.CharField(max_length=50, null=True)),
                ('kode_kel', models.CharField(max_length=50, null=True)),
                ('upk', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Kairagi Weru',
            },
        ),
        migrations.CreateModel(
            name='BnbaPaal2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50, null=True)),
                ('no_rumah', models.CharField(max_length=50, null=True)),
                ('lingkungan', models.CharField(max_length=50, null=True)),
                ('kode_foto', models.CharField(max_length=50, null=True)),
                ('stat', models.CharField(max_length=50, null=True)),
                ('path_foto', models.CharField(max_length=100, null=True)),
                ('trans_id', models.CharField(max_length=50, null=True)),
                ('kode_kec', models.CharField(max_length=50, null=True)),
                ('kode_kel', models.CharField(max_length=50, null=True)),
                ('upk', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Paal 2',
            },
        ),
        migrations.CreateModel(
            name='BnbaPerkamil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=50, null=True)),
                ('no_rumah', models.CharField(max_length=50, null=True)),
                ('lingkungan', models.CharField(max_length=50, null=True)),
                ('kode_foto', models.CharField(max_length=50, null=True)),
                ('stat', models.CharField(max_length=50, null=True)),
                ('path_foto', models.CharField(max_length=100, null=True)),
                ('trans_id', models.CharField(max_length=50, null=True)),
                ('kode_kec', models.CharField(max_length=50, null=True)),
                ('kode_kel', models.CharField(max_length=50, null=True)),
                ('upk', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32651)),
            ],
            options={
                'verbose_name': 'Perkamil',
            },
        ),
    ]
